name: auto-generate-gitbook
on:                                 #在main分支上进行push时触发
  push:
    branches:
      - main
defaults:
  run:
    working-directory: gitbook
jobs:
  main-to-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: main

      - name: install
        uses: actions/setup-node@v1

      - name: configue
        run: |
          npm install -g gitbook-cli
          gitbook install
          npm install -g gitbook-summary

      - name: generate
        run: |
          book sm
          gitbook build
          cp SUMMARY.md _book

      - name: push
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          repository-name: algorithm-go
          folder: gitbook/_book
          clean: true
